export const LOGIN_ASYNC_REQUEST = "LOGIN_ASYNC_REQUEST";

export const LOGIN_ON_REQUEST = "LOGIN_ON_REQUEST";
export const LOGIN_ON_SUCCESS = "LOGIN_ON_SUCCESS";
export const LOGIN_ON_FAILURE = "LOGIN_ON_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";