export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const DELETE_TASK = 'DELETE_TASK';
export const EDIT_TASK_MODE = 'EDIT_TASK_MODE';
export const SAVE_EDIT_TASK = 'SAVE_EDIT_TASK';
export const CANCEL_EDIT_TASK = 'CANCEL_EDIT_TASK';
export const TOGGLE_TASK = 'TOGGLE_TASK';
export const LOAD_TASKS = 'LOAD_TASKS';
export const SET_LOADED_TASKS = 'SET_LOADED_TASKS';

export const SET_CURRENT_TASK = 'SET_CURRENT_TASK';